/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BaiTap;

/**
 *
 * @author lythehoc
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hienThi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nut1 = new javax.swing.JButton();
        nut2 = new javax.swing.JButton();
        nut3 = new javax.swing.JButton();
        nutChia = new javax.swing.JButton();
        nutSqrt = new javax.swing.JButton();
        nut4 = new javax.swing.JButton();
        nut5 = new javax.swing.JButton();
        nut6 = new javax.swing.JButton();
        nutNhan = new javax.swing.JButton();
        nutPhanTram = new javax.swing.JButton();
        nut7 = new javax.swing.JButton();
        nut8 = new javax.swing.JButton();
        nut9 = new javax.swing.JButton();
        nutTru = new javax.swing.JButton();
        nutMotChia = new javax.swing.JButton();
        nut0 = new javax.swing.JButton();
        nutCT = new javax.swing.JButton();
        nutC = new javax.swing.JButton();
        nutCong = new javax.swing.JButton();
        nutBang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        hienThi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hienThi.setText("0");

        jPanel2.setLayout(new java.awt.GridLayout(4, 5));

        nut1.setText("1");
        nut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut1ActionPerformed(evt);
            }
        });
        jPanel2.add(nut1);

        nut2.setText("2");
        nut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut2ActionPerformed(evt);
            }
        });
        jPanel2.add(nut2);

        nut3.setText("3");
        nut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut3ActionPerformed(evt);
            }
        });
        jPanel2.add(nut3);

        nutChia.setText("/");
        nutChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutChiaActionPerformed(evt);
            }
        });
        jPanel2.add(nutChia);

        nutSqrt.setText("sqrt");
        nutSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutSqrtActionPerformed(evt);
            }
        });
        jPanel2.add(nutSqrt);

        nut4.setText("4");
        nut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut4ActionPerformed(evt);
            }
        });
        jPanel2.add(nut4);

        nut5.setText("5");
        nut5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut5ActionPerformed(evt);
            }
        });
        jPanel2.add(nut5);

        nut6.setText("6");
        nut6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut6ActionPerformed(evt);
            }
        });
        jPanel2.add(nut6);

        nutNhan.setText("*");
        nutNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutNhanActionPerformed(evt);
            }
        });
        jPanel2.add(nutNhan);

        nutPhanTram.setText("%");
        nutPhanTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutPhanTramActionPerformed(evt);
            }
        });
        jPanel2.add(nutPhanTram);

        nut7.setText("7");
        nut7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut7ActionPerformed(evt);
            }
        });
        jPanel2.add(nut7);

        nut8.setText("8");
        nut8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut8ActionPerformed(evt);
            }
        });
        jPanel2.add(nut8);

        nut9.setText("9");
        nut9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut9ActionPerformed(evt);
            }
        });
        jPanel2.add(nut9);

        nutTru.setText("-");
        nutTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutTruActionPerformed(evt);
            }
        });
        jPanel2.add(nutTru);

        nutMotChia.setText("1/X");
        jPanel2.add(nutMotChia);

        nut0.setText("0");
        nut0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut0ActionPerformed(evt);
            }
        });
        jPanel2.add(nut0);

        nutCT.setText("+/-");
        nutCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutCTActionPerformed(evt);
            }
        });
        jPanel2.add(nutCT);

        nutC.setText("C");
        jPanel2.add(nutC);

        nutCong.setText("+");
        nutCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutCongActionPerformed(evt);
            }
        });
        jPanel2.add(nutCong);

        nutBang.setText("=");
        nutBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutBangActionPerformed(evt);
            }
        });
        jPanel2.add(nutBang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private long a=0;
    private String phepToan="";
    private void nut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut1ActionPerformed
    String gt=this.hienThi.getText();
    if (gt.length()<12){
        if (gt.equals("0")) gt="";
        long so=Long.parseLong(gt+ nut1.getText());
        this.hienThi.setText(String.valueOf(so));
    }   
    }//GEN-LAST:event_nut1ActionPerformed

    private void nutChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutChiaActionPerformed
      this.a = Long.parseLong(this.hienThi.getText());
       if (this.a !=0){
           this.phepToan = "/";
           this.hienThi.setText("0");
       }
    }//GEN-LAST:event_nutChiaActionPerformed

    private void nutSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutSqrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nutSqrtActionPerformed

    private void nutPhanTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutPhanTramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nutPhanTramActionPerformed

    private void nut8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut8ActionPerformed
      String gt=this.hienThi.getText();
    if (gt.length()<12){
        if (gt.equals("0")) gt="";
        long so=Long.parseLong(gt+ nut8.getText());
        this.hienThi.setText(String.valueOf(so));
    }   
    }//GEN-LAST:event_nut8ActionPerformed

    private void nutTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutTruActionPerformed
       this.a = Long.parseLong(this.hienThi.getText());
        this.phepToan = "-";
        this.hienThi.setText("0");
    }//GEN-LAST:event_nutTruActionPerformed

    private void nutCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nutCTActionPerformed

    private void nut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut4ActionPerformed
       String gt=this.hienThi.getText();
    if (gt.length()<12){
        if (gt.equals("0")) gt="";
        long so=Long.parseLong(gt+ nut4.getText());
        this.hienThi.setText(String.valueOf(so));
    }   
    }//GEN-LAST:event_nut4ActionPerformed

    private void nut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut2ActionPerformed
        String gt=this.hienThi.getText();
    if (gt.length()<12){
        if (gt.equals("0")) gt="";
        long so=Long.parseLong(gt+ nut2.getText());
        this.hienThi.setText(String.valueOf(so));
    }   
    }//GEN-LAST:event_nut2ActionPerformed

    private void nut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut3ActionPerformed
        String gt=this.hienThi.getText();
    if (gt.length()<12){
        if (gt.equals("0")) gt="";
        long so=Long.parseLong(gt+ nut3.getText());
        this.hienThi.setText(String.valueOf(so));
    }   
    }//GEN-LAST:event_nut3ActionPerformed

    private void nut5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut5ActionPerformed
       String gt=this.hienThi.getText();
    if (gt.length()<12){
        if (gt.equals("0")) gt="";
        long so=Long.parseLong(gt+ nut5.getText());
        this.hienThi.setText(String.valueOf(so));
    }   
    }//GEN-LAST:event_nut5ActionPerformed

    private void nut6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut6ActionPerformed
        String gt=this.hienThi.getText();
    if (gt.length()<12){
        if (gt.equals("0")) gt="";
        long so=Long.parseLong(gt+ nut6.getText());
        this.hienThi.setText(String.valueOf(so));
    }   
    }//GEN-LAST:event_nut6ActionPerformed

    private void nut7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut7ActionPerformed
       String gt=this.hienThi.getText();
    if (gt.length()<12){
        if (gt.equals("0")) gt="";
        long so=Long.parseLong(gt+ nut7.getText());
        this.hienThi.setText(String.valueOf(so));
    }   
    }//GEN-LAST:event_nut7ActionPerformed

    private void nut9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut9ActionPerformed
        String gt=this.hienThi.getText();
    if (gt.length()<12){
        if (gt.equals("0")) gt="";
        long so=Long.parseLong(gt+ nut9.getText());
        this.hienThi.setText(String.valueOf(so));
    }   
    }//GEN-LAST:event_nut9ActionPerformed

    private void nut0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut0ActionPerformed
       String gt=this.hienThi.getText();
    if (gt.length()<12){
        if (gt.equals("0")) gt="";
        long so=Long.parseLong(gt+ nut0.getText());
        this.hienThi.setText(String.valueOf(so));
    }   
    }//GEN-LAST:event_nut0ActionPerformed

    private void nutNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutNhanActionPerformed
       this.a = Long.parseLong(this.hienThi.getText());
        this.phepToan = "*";
        this.hienThi.setText("0");
    }//GEN-LAST:event_nutNhanActionPerformed

    private void nutCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutCongActionPerformed
        this.a = Long.parseLong(this.hienThi.getText());
        this.phepToan = "+";
        this.hienThi.setText("0");
    }//GEN-LAST:event_nutCongActionPerformed

    private void nutBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutBangActionPerformed
       if (this.phepToan.length()>0){
            long b=Long.parseLong(this.hienThi.getText());
            if(this.phepToan.equals("+")){
                long kq=this.a+b;
                this.hienThi.setText(String.valueOf(kq));
                
            }else if(this.phepToan.equals("-")){
                long kq = this.a - b;
                this.hienThi.setText(String.valueOf(kq));
            }else if (this.phepToan.equals("*")){
                long kq=this.a*b;
                this.hienThi.setText(String.valueOf(kq));
            }else if (this.phepToan.equals("/")){
                float kq=(float)this.a/b;
                this.hienThi.setText(String.valueOf(kq));
            }
            this.phepToan = "";
            this.a=0;
        }
    }//GEN-LAST:event_nutBangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hienThi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nut0;
    private javax.swing.JButton nut1;
    private javax.swing.JButton nut2;
    private javax.swing.JButton nut3;
    private javax.swing.JButton nut4;
    private javax.swing.JButton nut5;
    private javax.swing.JButton nut6;
    private javax.swing.JButton nut7;
    private javax.swing.JButton nut8;
    private javax.swing.JButton nut9;
    private javax.swing.JButton nutBang;
    private javax.swing.JButton nutC;
    private javax.swing.JButton nutCT;
    private javax.swing.JButton nutChia;
    private javax.swing.JButton nutCong;
    private javax.swing.JButton nutMotChia;
    private javax.swing.JButton nutNhan;
    private javax.swing.JButton nutPhanTram;
    private javax.swing.JButton nutSqrt;
    private javax.swing.JButton nutTru;
    // End of variables declaration//GEN-END:variables
}
